spring:
  application:
    name: api-gateway
  redis:
    connect-timeout: 1s
    host: localhost
    port: 6379
    timeout: 2000ms

  cloud:
    gateway:
      default-filters:
      routes:
        - id: custom-service
          uri: http://localhost:8080/
          predicates:
            - Path=/custom/**
          filters:
            - RewritePath=/custom/(?<path>.*), /$\{path}
server:
  port: 8765
